/**
 * Autogenerated with Blossom Toolbelt v0.0.0.
 *
 * DO NOT MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING.
 */

import { Maybe, QueryResolverSignature } from '@blossom-gql/core';

import { RequestContext } from 'blossom/instance';

export type Example = {
  /**
   * Required by GraphQL.js. Must match the name of the object in the GraphQL SDL
   * this type is representing in the codebase.
   */
  __typename: 'Example';
  name: string;
  message: string;
};

export type ExampleQuery = QueryResolverSignature<
  {
    names: ReadonlyArray<string>;
  },
  Promise<ReadonlyArray<Maybe<Example>>>,
  RequestContext
>;
